spring.application.name=aswindows

spring.profiles.active=local

server.port=8842

spring.mvc.view.prefix=/WEB-INF/views/assets/
spring.mvc.view.suffix=.jsp
server.error.whitelabel.enabled=false
server.error.path=/error

spring.main.allow-bean-definition-overriding=true
spring.web.resources.cache.cachecontrol.max-age=68000
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

#file config upload file excel
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.type=trace
logging.level.org.hibernate.stat=debug

logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security=DEBUG
